from typing import Optional

CURRICULUM: dict[str, dict[str, list[str]]] = {
    "10": {
        "Science": [
            "Chapter 1: Chemical Reactions and Equations",
            "Chapter 2: Acids, Bases and Salts",
            "Chapter 3: Metals and Non-metals",
            "Chapter 4: Carbon and its Compounds",
            "Chapter 5: Life Processes",
            "Chapter 6: Control and Coordination",
            "Chapter 7: How do Organisms Reproduce",
            "Chapter 8: Heredity",
            "Chapter 9: Light – Reflection and Refraction",
            "Chapter 10: The Human Eye and the Colourful World",
            "Chapter 11: Electricity",
            "Chapter 12: Magnetic Effects of Electric Current",
            "Chapter 13: Our Environment",
        ],
        "Mathematics": [
            "Chapter 1: Real Numbers",
            "Chapter 2: Polynomials",
            "Chapter 3: Pair of Linear Equations in Two Variables",
            "Chapter 4: Quadratic Equations",
            "Chapter 5: Arithmetic Progressions",
            "Chapter 6: Triangles",
            "Chapter 7: Coordinate Geometry",
            "Chapter 8: Introduction to Trigonometry",
            "Chapter 9: Some Applications of Trigonometry",
            "Chapter 10: Circles",
            "Chapter 11: Areas Related to Circles",
            "Chapter 12: Surface Areas and Volumes",
            "Chapter 13: Statistics",
            "Chapter 14: Probability",
        ],
        "Social Science": [
            "History: Chapter 1: The Rise of Nationalism in Europe",
            "History: Chapter 2: Nationalism in India",
            "History: Chapter 3: The Making of a Global World",
            "History: Chapter 4: The Age of Industrialisation",
            "History: Chapter 5: Print Culture and the Modern World",
            "Geography: Chapter 1: Resources and Development",
            "Geography: Chapter 2: Forest and Wildlife Resources",
            "Geography: Chapter 3: Water Resources",
            "Geography: Chapter 4: Agriculture",
            "Geography: Chapter 5: Minerals and Energy Resources",
            "Geography: Chapter 6: Manufacturing Industries",
            "Geography: Chapter 7: Lifelines of National Economy",
            "Civics: Chapter 1: Power-sharing",
            "Civics: Chapter 2: Federalism",
            "Civics: Chapter 3: Democracy and Diversity",
            "Civics: Chapter 4: Gender, Religion and Caste",
            "Civics: Chapter 5: Popular Struggles and Movements",
            "Civics: Chapter 6: Political Parties",
            "Civics: Chapter 7: Outcomes of Democracy",
            "Civics: Chapter 8: Challenges to Democracy",
            "Economics: Chapter 1: Development",
            "Economics: Chapter 2: Sectors of the Indian Economy",
            "Economics: Chapter 3: Money and Credit",
            "Economics: Chapter 4: Globalisation and the Indian Economy",
            "Economics: Chapter 5: Consumer Rights",
        ],
        "English": [
            "First Flight: Chapter 1: A Letter to God",
            "First Flight: Chapter 2: Nelson Mandela: Long Walk to Freedom",
            "First Flight: Chapter 3: Two Stories About Flying",
            "First Flight: Chapter 4: From the Diary of Anne Frank",
            "First Flight: Chapter 5: Glimpses of India",
            "First Flight: Chapter 6: Mijbil the Otter",
            "First Flight: Chapter 7: Madam Rides the Bus",
            "First Flight: Chapter 8: The Sermon at Benares",
            "First Flight: Chapter 9: The Proposal",
            "Footprints Without Feet: Chapter 1: A Triumph of Surgery",
            "Footprints Without Feet: Chapter 2: The Thief's Story",
            "Footprints Without Feet: Chapter 3: The Midnight Visitor",
            "Footprints Without Feet: Chapter 4: A Question of Trust",
            "Footprints Without Feet: Chapter 5: Footprints Without Feet",
            "Footprints Without Feet: Chapter 6: The Making of a Scientist",
            "Footprints Without Feet: Chapter 7: The Necklace",
            "Footprints Without Feet: Chapter 8: The Hack Driver",
            "Footprints Without Feet: Chapter 9: Bholi",
            "Footprints Without Feet: Chapter 10: The Book that Saved the Earth",
        ],
    },
    "11": {
        "Physics": [
            "Chapter 1: Physical World",
            "Chapter 2: Units and Measurements",
            "Chapter 3: Motion in a Straight Line",
            "Chapter 4: Motion in a Plane",
            "Chapter 5: Laws of Motion",
            "Chapter 6: Work, Energy and Power",
            "Chapter 7: System of Particles and Rotational Motion",
            "Chapter 8: Gravitation",
            "Chapter 9: Mechanical Properties of Solids",
            "Chapter 10: Mechanical Properties of Fluids",
            "Chapter 11: Thermal Properties of Matter",
            "Chapter 12: Thermodynamics",
            "Chapter 13: Kinetic Theory",
            "Chapter 14: Oscillations",
            "Chapter 15: Waves",
        ],
        "Chemistry": [
            "Chapter 1: Some Basic Concepts of Chemistry",
            "Chapter 2: Structure of Atom",
            "Chapter 3: Classification of Elements and Periodicity",
            "Chapter 4: Chemical Bonding and Molecular Structure",
            "Chapter 5: Thermodynamics",
            "Chapter 6: Equilibrium",
            "Chapter 7: Redox Reactions",
            "Chapter 8: Organic Chemistry: Some Basic Principles",
            "Chapter 9: Hydrocarbons",
        ],
        "Biology": [
            "Chapter 1: The Living World",
            "Chapter 2: Biological Classification",
            "Chapter 3: Plant Kingdom",
            "Chapter 4: Animal Kingdom",
            "Chapter 5: Morphology of Flowering Plants",
            "Chapter 6: Anatomy of Flowering Plants",
            "Chapter 7: Structural Organization in Animals",
            "Chapter 8: Cell: The Unit of Life",
            "Chapter 9: Biomolecules",
            "Chapter 10: Cell Cycle and Cell Division",
            "Chapter 11: Transport in Plants",
            "Chapter 12: Mineral Nutrition",
            "Chapter 13: Photosynthesis in Higher Plants",
            "Chapter 14: Respiration in Plants",
            "Chapter 15: Plant Growth and Development",
            "Chapter 16: Digestion and Absorption",
            "Chapter 17: Breathing and Exchange of Gases",
            "Chapter 18: Body Fluids and Circulation",
            "Chapter 19: Excretory Products and Elimination",
            "Chapter 20: Locomotion and Movement",
            "Chapter 21: Neural Control and Coordination",
            "Chapter 22: Chemical Coordination and Integration",
        ],
        "Mathematics": [
            "Chapter 1: Sets",
            "Chapter 2: Relations and Functions",
            "Chapter 3: Trigonometric Functions",
            "Chapter 4: Complex Numbers and Quadratic Equations",
            "Chapter 5: Linear Inequalities",
            "Chapter 6: Permutations and Combinations",
            "Chapter 7: Binomial Theorem",
            "Chapter 8: Sequences and Series",
            "Chapter 9: Straight Lines",
            "Chapter 10: Conic Sections",
            "Chapter 11: Introduction to Three Dimensional Geometry",
            "Chapter 12: Limits and Derivatives",
            "Chapter 13: Statistics",
            "Chapter 14: Probability",
        ],
        "English": [
            "Hornbill: Chapter 1: The Portrait of a Lady",
            "Hornbill: Chapter 2: We're Not Afraid to Die",
            "Hornbill: Chapter 3: Discovering Tut: The Saga Continues",
            "Hornbill: Chapter 4: Landscape of the Soul",
            "Hornbill: Chapter 5: The Ailing Planet",
            "Hornbill: Chapter 6: The Browning Version",
            "Hornbill: Chapter 7: The Adventure",
            "Hornbill: Chapter 8: Silk Road",
            "Snapshots: Chapter 1: The Summer of the Beautiful White Horse",
            "Snapshots: Chapter 2: The Address",
            "Snapshots: Chapter 3: Ranga's Marriage",
            "Snapshots: Chapter 4: Albert Einstein at School",
            "Snapshots: Chapter 5: Mother's Day",
            "Snapshots: Chapter 6: The Ghat of the Only World",
            "Snapshots: Chapter 7: Birth",
            "Snapshots: Chapter 8: The Tale of Melon City",
        ],
        "Computer Science": [
            "Chapter 1: Computer System",
            "Chapter 2: Encoding Schemes and Number System",
            "Chapter 3: Emerging Trends",
            "Chapter 4: Introduction to Problem Solving",
            "Chapter 5: Getting Started with Python",
            "Chapter 6: Flow of Control",
            "Chapter 7: Functions",
            "Chapter 8: Strings",
            "Chapter 9: Lists",
            "Chapter 10: Tuples and Dictionaries",
            "Chapter 11: Societal Impact",
        ],
        "Accountancy": [
            "Chapter 1: Introduction to Accounting",
            "Chapter 2: Theory Base of Accounting",
            "Chapter 3: Recording of Transactions – I",
            "Chapter 4: Recording of Transactions – II",
            "Chapter 5: Bank Reconciliation Statement",
            "Chapter 6: Trial Balance and Rectification of Errors",
            "Chapter 7: Depreciation, Provisions and Reserves",
            "Chapter 8: Bill of Exchange",
            "Chapter 9: Financial Statements – I",
            "Chapter 10: Financial Statements – II",
        ],
        "Business Studies": [
            "Chapter 1: Business, Trade and Commerce",
            "Chapter 2: Forms of Business Organisation",
            "Chapter 3: Private, Public and Global Enterprises",
            "Chapter 4: Business Services",
            "Chapter 5: Emerging Modes of Business",
            "Chapter 6: Social Responsibilities of Business",
            "Chapter 7: Formation of a Company",
            "Chapter 8: Sources of Business Finance",
            "Chapter 9: Small Business",
            "Chapter 10: Internal Trade",
            "Chapter 11: International Business",
        ],
        "Economics": [
            "Statistics: Chapter 1: Introduction",
            "Statistics: Chapter 2: Collection of Data",
            "Statistics: Chapter 3: Organisation of Data",
            "Statistics: Chapter 4: Presentation of Data",
            "Statistics: Chapter 5: Measures of Central Tendency",
            "Statistics: Chapter 6: Measures of Dispersion",
            "Statistics: Chapter 7: Correlation",
            "Statistics: Chapter 8: Index Numbers",
            "Micro: Chapter 1: Introduction",
            "Micro: Chapter 2: Theory of Consumer Behaviour",
            "Micro: Chapter 3: Production and Costs",
            "Micro: Chapter 4: The Theory of the Firm",
            "Micro: Chapter 5: Market Equilibrium",
            "Micro: Chapter 6: Non-competitive Markets",
        ],
    },
    "12": {
        "Physics": [
            "Chapter 1: Electric Charges and Fields",
            "Chapter 2: Electrostatic Potential and Capacitance",
            "Chapter 3: Current Electricity",
            "Chapter 4: Moving Charges and Magnetism",
            "Chapter 5: Magnetism and Matter",
            "Chapter 6: Electromagnetic Induction",
            "Chapter 7: Alternating Current",
            "Chapter 8: Electromagnetic Waves",
            "Chapter 9: Ray Optics and Optical Instruments",
            "Chapter 10: Wave Optics",
            "Chapter 11: Dual Nature of Radiation and Matter",
            "Chapter 12: Atoms",
            "Chapter 13: Nuclei",
            "Chapter 14: Semiconductor Electronics",
            "Chapter 15: Communication Systems",
        ],
        "Chemistry": [
            "Chapter 1: Solutions",
            "Chapter 2: Electrochemistry",
            "Chapter 3: Chemical Kinetics",
            "Chapter 4: The d- and f-Block Elements",
            "Chapter 5: Coordination Compounds",
            "Chapter 6: Haloalkanes and Haloarenes",
            "Chapter 7: Alcohols, Phenols and Ethers",
            "Chapter 8: Aldehydes, Ketones and Carboxylic Acids",
            "Chapter 9: Amines",
            "Chapter 10: Biomolecules",
            "Chapter 11: Polymers",
            "Chapter 12: Chemistry in Everyday Life",
        ],
        "Biology": [
            "Chapter 1: Reproduction in Organisms",
            "Chapter 2: Sexual Reproduction in Flowering Plants",
            "Chapter 3: Human Reproduction",
            "Chapter 4: Reproductive Health",
            "Chapter 5: Principles of Inheritance and Variation",
            "Chapter 6: Molecular Basis of Inheritance",
            "Chapter 7: Evolution",
            "Chapter 8: Human Health and Disease",
            "Chapter 9: Strategies for Enhancement in Food Production",
            "Chapter 10: Microbes in Human Welfare",
            "Chapter 11: Biotechnology: Principles and Processes",
            "Chapter 12: Biotechnology and its Applications",
            "Chapter 13: Organisms and Populations",
            "Chapter 14: Ecosystem",
            "Chapter 15: Biodiversity and Conservation",
            "Chapter 16: Environmental Issues",
        ],
        "Mathematics": [
            "Chapter 1: Relations and Functions",
            "Chapter 2: Inverse Trigonometric Functions",
            "Chapter 3: Matrices",
            "Chapter 4: Determinants",
            "Chapter 5: Continuity and Differentiability",
            "Chapter 6: Application of Derivatives",
            "Chapter 7: Integrals",
            "Chapter 8: Application of Integrals",
            "Chapter 9: Differential Equations",
            "Chapter 10: Vector Algebra",
            "Chapter 11: Three Dimensional Geometry",
            "Chapter 12: Linear Programming",
            "Chapter 13: Probability",
        ],
        "English": [
            "Flamingo: Chapter 1: The Last Lesson",
            "Flamingo: Chapter 2: Lost Spring",
            "Flamingo: Chapter 3: Deep Water",
            "Flamingo: Chapter 4: The Rattrap",
            "Flamingo: Chapter 5: Indigo",
            "Flamingo: Chapter 6: Poets and Pancakes",
            "Flamingo: Chapter 7: The Interview",
            "Flamingo: Chapter 8: Going Places",
            "Vistas: Chapter 1: The Third Level",
            "Vistas: Chapter 2: The Tiger King",
            "Vistas: Chapter 3: The Enemy",
            "Vistas: Chapter 4: Journey to the End of the Earth",
            "Vistas: Chapter 5: Should Wizard Hit Mommy",
            "Vistas: Chapter 6: On the Face of It",
            "Vistas: Chapter 7: Evans Tries an O-level",
            "Vistas: Chapter 8: Memories of Childhood",
        ],
        "Computer Science": [
            "Chapter 1: Exception Handling in Python",
            "Chapter 2: File Handling in Python",
            "Chapter 3: Stack",
            "Chapter 4: Queue",
            "Chapter 5: Searching",
            "Chapter 6: Sorting",
            "Chapter 7: Understanding Data",
            "Chapter 8: Database Concepts",
            "Chapter 9: Structured Query Language",
            "Chapter 10: Computer Networks",
            "Chapter 11: Data Communication",
            "Chapter 12: Security Aspects",
        ],
        "Accountancy": [
            "Chapter 1: Accounting for Share Capital",
            "Chapter 2: Issue and Redemption of Debentures",
            "Chapter 3: Financial Statements of a Company",
            "Chapter 4: Analysis of Financial Statements",
            "Chapter 5: Accounting Ratios",
            "Chapter 6: Cash Flow Statement",
            "Chapter 7: Dissolution of Partnership Firm",
            "Chapter 8: Accounting for Partnership: Basic Concepts",
            "Chapter 9: Reconstitution of a Partnership Firm",
            "Chapter 10: Accounting for Share Capital",
        ],
        "Business Studies": [
            "Chapter 1: Nature and Significance of Management",
            "Chapter 2: Principles of Management",
            "Chapter 3: Business Environment",
            "Chapter 4: Planning",
            "Chapter 5: Organising",
            "Chapter 6: Staffing",
            "Chapter 7: Directing",
            "Chapter 8: Controlling",
            "Chapter 9: Financial Management",
            "Chapter 10: Financial Markets",
            "Chapter 11: Marketing Management",
            "Chapter 12: Consumer Protection",
        ],
        "Economics": [
            "Macro: Chapter 1: Introduction to Macroeconomics",
            "Macro: Chapter 2: National Income Accounting",
            "Macro: Chapter 3: Money and Banking",
            "Macro: Chapter 4: Determination of Income and Employment",
            "Macro: Chapter 5: Government Budget and the Economy",
            "Macro: Chapter 6: Open Economy Macroeconomics",
            "Indian Eco: Chapter 1: Indian Economy on the Eve of Independence",
            "Indian Eco: Chapter 2: Indian Economy 1950–1990",
            "Indian Eco: Chapter 3: Economic Reforms Since 1991",
            "Indian Eco: Chapter 4: Poverty",
            "Indian Eco: Chapter 5: Human Capital Formation in India",
            "Indian Eco: Chapter 6: Rural Development",
            "Indian Eco: Chapter 7: Employment: Growth, Informalisation",
            "Indian Eco: Chapter 8: Infrastructure",
            "Indian Eco: Chapter 9: Environment and Sustainable Development",
            "Indian Eco: Chapter 10: Comparative Development Experiences",
        ],
    },
}

SUBJECT_ALIASES: dict[str, str] = {
    "science": "Science",
    "physics": "Physics",
    "chemistry": "Chemistry",
    "biology": "Biology",
    "math": "Mathematics",
    "maths": "Mathematics",
    "mathematics": "Mathematics",
    "social": "Social Science",
    "social science": "Social Science",
    "sst": "Social Science",
    "english": "English",
    "hindi": "Hindi",
    "cs": "Computer Science",
    "computer": "Computer Science",
    "comp sci": "Computer Science",
    "eco": "Economics",
    "economics": "Economics",
    "accts": "Accountancy",
    "accountancy": "Accountancy",
    "bst": "Business Studies",
    "business": "Business Studies",
    "business studies": "Business Studies",
}


def resolve_subject(raw: str) -> Optional[str]:
    return SUBJECT_ALIASES.get(raw.strip().lower())


def get_chapters(class_std: str, subject: str) -> Optional[list[str]]:
    cls_data = CURRICULUM.get(class_std)
    if not cls_data:
        return None
    chapters = cls_data.get(subject)
    if chapters:
        return chapters
    resolved = resolve_subject(subject)
    if resolved:
        return cls_data.get(resolved)
    return None


def get_context_block(class_std: str, subject: str, chapter: Optional[str] = None) -> str:
    chapters = get_chapters(class_std, subject)
    if not chapters:
        return ""
    lines = [f"\n=== NCERT Curriculum: Class {class_std} {subject} ==="]
    lines.append("Refer to these NCERT chapters when answering:")
    for ch in chapters:
        marker = " → *" if chapter and chapter.lower() in ch.lower() else ""
        lines.append(f"  {ch}{marker}")
    return "\n".join(lines)
